import pytest 
from unittest.mock import  MagicMock, patch
from fastapi.testclient import TestClient

# --- Mocking External Services # A mock is a fake object used in tests to pretend to be a real thing.
# We must mock this BEFORE importing app.py because app.py connects on load.

# 1. Mock Pinecone client
mock_pc_module = MagicMock()
mock_pc_instance = MagicMock()
mock_pc_instance.list_index.return_value.names.return_value = ["modern-rag"] # Pretend index exists
mock_pc_module.Pinecone.return_value = mock_pc_instance

# 2. Mock VectorStore
mock_vs_module = MagicMock()

# 3. Mock OpenAI/LangChain
mock_chat_module = MagicMock()
mock_embedding_module = MagicMock()

# Apply patches : temporarily replace something during a test
with patch.dict("sys.modules",{ 
    "pinecone" : mock_pc_module,
    "langchain_pinecone": mock_vs_module,
    "langchain_openai" : mock_chat_module,
    "langchain_community.embeddings" : mock_embedding_module
}):
    # Now we can import the app safely
    from app import app
    
# Initiazlie Test Client
client = TestClient(app)

# --- TESTS ---

def test_index_stats():
    """Test the /index/state endpoint"""
    response = client.get("/index/state")
    assert response.status_code ==200 #this must be true — otherwise, the test fails.
    # Check if the structure matches your Pydantic model
    assert "total_vectorstore" in response.json()
    
def test_query_rag_mocked():
    """Test the /query endpoint with a mocked graph response"""
    
    # We need to mock the 'rag_graph' inside the app
    with patch("app.rag_graph") as mock_graph:
        # Define what the graph returns when ainvoke is called
        mock_graph.ainvoke.return_value= {
            "query" : "rewritten query",
            "answer" : "This is a mocked answer generated by tests.",
            "documents": [
                MagicMock(page_content= "Mock content", metadata= {"filename": "test.pdf"})
            ]
        }
        
        payload = {"query": "What is in the document?", "session_id": "test-123"}
        response = client.post("/query", json=payload)
        
        assert response.status_code == 200
        data = response.json()
        assert data["answer"] == "This is a mocked answer generated by tests."
        assert data["num_source_used"] == 1
    
