import pytest
from unittest.mock import MagicMock, patch
from fastapi.testclient import TestClient

# --- MOCKING EXTERNAL SERVICES ---
# We mock these modules so the real app.py doesn't try to connect to OpenAI/Pinecone
mock_pc_module = MagicMock()
mock_pc_instance = MagicMock()
mock_pc_instance.list_indexes.return_value.names.return_value = ["modern-rag"]
mock_pc_module.Pinecone.return_value = mock_pc_instance

mock_vs_module = MagicMock()
mock_chat_module = MagicMock()
mock_embeddings_module = MagicMock()

# Apply patches to sys.modules
with patch.dict("sys.modules", {
    "pinecone": mock_pc_module,
    "langchain_pinecone": mock_vs_module,
    "langchain_openai": mock_chat_module,
    "langchain_community.embeddings": mock_embeddings_module,
}):
    # Import app AFTER mocking
    from app import app

client = TestClient(app)

# --- TESTS ---

def test_index_stats():
    """Test the /index/state endpoint"""
    response = client.get("/index/state")
    assert response.status_code == 200
    
    # Ensure you fixed the typo in app.py ('total_vectorstore'), 
    # otherwise change this string to 'total_vectostore' to match your code.
    assert "total_vectorstore" in response.json() 

def test_query_rag_mocked():
    """Test the /query endpoint with a mocked graph response"""
    
    # FIX: Use patch.object on the imported 'app' module directly
    # This prevents re-importing the file and causing the Pydantic error
    with patch.object(app, "rag_graph") as mock_graph:
        
        # Configure the mock to return our fake data
        mock_graph.ainvoke.return_value = {
            "query": "rewritten query",
            "answer": "This is a mocked answer generated by tests.",
            "documents": [
                MagicMock(page_content="Mock content", metadata={"filename": "test.pdf"})
            ]
        }

        payload = {"query": "What is in the document?", "session_id": "test-123"}
        response = client.post("/query", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert data["answer"] == "This is a mocked answer generated by tests."
        assert data["num_source_used"] == 1